# This is a basic workflow to help you get started with Actions

name: pytest

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_on_linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: clone repository
        run: |
          git clone https://github.com/wckjob/workflows/blob/main/test_test1.py
          cd github-actions-python
      - name: install pytest
        run: pip install pytest
      - name run pytest
        run: pytest
